### ISSUE TITLE
Not able to load package

### ISSUE THREAD

**Issue by emmacooperpeterson** [leeper/slopegraph#19]
**When I run this:**

if (!require("ghit")) {
    install.packages("ghit")
}
ghit::install_github("leeper/slopegraph")

**I get this error:**

Error in read.dcf(file = tmpf) : cannot open the connection
In addition: Warning message:
In read.dcf(file = tmpf) :
  cannot open compressed file '//var/folders/d6/vj5j60497bs_kc9z28wc3j6c0000gn/T//RtmpeVYawE/ghitdrat/src/contrib/PACKAGES', probable reason 'No such file or directory'

**Comment by leeper** [comment]
Try `devtools::install_github("leeper/slopegraph")` instead.
