### ISSUE TITLE
Request to take over development of slopegraph...

### ISSUE THREAD

**Issue by JustinMShea** [leeper/slopegraph#23]
...with the goal of getting it on CRAN!

**Comment by leeper** [comment]
Awesome!! I've just sent you an invite. Let me know how you'd like to proceed - we can transfer this over to your account or you can edit here. Either is totally fine with me. Thank you so much!!

**Comment by JustinMShea** [comment]
Sounds good, let me think about it! Thank you!

**Comment by JustinMShea** [comment]
Dear Thomas, 
Thank you for agreeing to pass the proverbial torch regarding slopegraph. Regretfully my circumstances for taking this on have changed dramatically over the last month. I think the good work of Chuck Powell @ibcev makes him the best candidate for taking it on at this time! Do you agree?
