### ISSUE TITLE
Thanks and some thoughts

### ISSUE THREAD

**Issue by ibecav** [leeper/slopegraph#24]
I didn't do a pull request because it seems you all are in a bit of flux, but I did want to give you proper credit and a look at the slightly different way I approached the task I took a look at your base code and there's probably an opportunity to merge some pieces [here.
](https://ibecav.github.io/slopegraph/)

https://ibecav.github.io/slopegraph/

Thanks for your efforts. 

Chuck

**Comment by leeper** [comment]
Nice! Really glad to see you figured out a solution to the label overlap problem! Please consider submitting a PR or otherwise collaborating with @JustinMShea on this!

**Comment by ibecav** [comment]
Thanks.  @JustinMShea if I can helpful on the "gg" pieces give me a holler.

Chuck

**Comment by leeper** [comment]
Thanks for the PR over at #26.
