### ISSUE TITLE
ggslopegraph2 problem: not a data frame

### ISSUE THREAD

**Issue by bshor** [leeper/slopegraph#33]
ggslopegraph2 mostly works, except when it is called in a function. Then it complains about a dataframe I pass to it, complaining:

`Error: The first object in your list 'sg.df' does not exist. It should be a dataframe
`

My code is as follows:

```
    ggslopegraph2(sg.df, times=year, measurement=comp.diffs, grouping=st, title = NULL) +  
      theme_bw() + labs(x=NULL, y=NULL) + theme(legend.position = "none")

```

In the debugger I have verified that sg.df is absolutely a dataframe. What could be going on?

**Comment by bshor** [comment]
@ibecav fixed this in his excellent package [CGPFunctions](https://github.com/ibecav/CGPfunctions/), and specifically the [newggslopegraph ](https://ibecav.github.io/CGPfunctions/articles/Using-newggslopegraph.html)function. Thanks to Thomas for writing the package in the first place, and to Chuck for updating it!

**Comment by ibecav** [comment]
Thank you
