### ISSUE TITLE
Suggestion: Allow input data in long format

### ISSUE THREAD

**Issue by friendly** [leeper/slopegraph#35]
Wide format is most sensible, but it is untidy. It would be useful to allow input data to be in long format

**Comment by ibecav** [comment]
Dear Michael,

There is a slightly more feature rich version of the function here https://github.com/ibecav/CGPfunctions.

I agree people have their preferences about wide versus long but honestly given all the tools available like pivot_wider() I have no plans to change the function and will continue to let people shape their data the way they want on demand.

Chuck
