### ISSUE TITLE
col.lines[i] not working

### ISSUE THREAD

**Issue by pbradl42** [leeper/slopegraph#8]
col.lines is not working correcting in the function 'slopegraph'. It can be fixed easily, by adding 'n' to the cbind command that creates 'todraw' (line155), thus passing the index of the line in question to the apply function on line 157.  Then add the line ' i <- rowdata[5]' to the apply function (line 162, e.g.) and the lines will color as expected.

**Comment by leeper** [comment]
Can you send a Pull Request?

**Comment by pbradl42** [comment]
Done - thanks, and sorry for my learning curve with the git hub process-- even though I’m an old school UNIX guy, I haven’t been active in dev communities in some 20 years. 

Peter Bradley | Director of the Honors Program
Ferris State University
202 South Street, Pickell 142 | Big Rapids, MI 49307
peterbradley@ferris.edu | www.ferris.edu/honors/
@FerrisHonors | @pbradl42
231.591.2216

**Comment by leeper** [comment]
Thanks! And no worries.

Closed by #10

**Comment by pbradl42** [comment]
No problem!

Peter Bradley | Director of the Honors Program
Ferris State University
202 South Street, Pickell 142 | Big Rapids, MI 49307
peterbradley@ferris.edu | www.ferris.edu/honors/
@FerrisHonors | @pbradl42
231.591.2216
